version: 2.1

orbs:
  maven: circleci/maven@1.4.1

executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'
      - image: 'cimg/postgres:15.2'
        environment:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: java17
