version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  sdkman: joshdholtz/sdkman@0.2.0


jobs:
  arm64-native:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - sdkman/setup-sdkman
      - sdkman/sdkman-install:
          candidate: java
          version: 17.0.8-amzn
      - run:
          name: "Run Test"
          command: "./mvnw test"


workflows:
  arm64-native-workflow:
    jobs:
      - arm64-native:
          context:
            - aeros-ctx


# executors:
#   java17:
#     docker:
#       - image: 'cimg/openjdk:17.0'
#       - image: 'cimg/postgres:15.2'
#         environment:
#           POSTGRES_USERNAME: postgres
#           POSTGRES_PASSWORD: postgres

# workflows:
#   maven_test:
#     jobs:
#       - maven/test:
#           executor: java17
